# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Populacao',
            fields=[
                ('id_populacao', models.IntegerField(primary_key=True, serialize=False)),
                ('idade', models.IntegerField()),
                ('candidato', models.CharField(max_length=3)),
            ],
        ),
    ]
