version: '3'
# DEV SETTINGS
services:
    # Postgres
    db:
        image: postgres
        hostname: db
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "docker"
    # Django
    web:
        build:
            context: .
            dockerfile: dev-docker/Dockerfile
        env_file:
          - dev.env
        hostname: web
        command: ./dev-docker/run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8000:8000"
